<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pengaduan extends Model
{
    use HasFactory;

    protected $table = 'pengaduan';

    protected $fillable = [
        'kode_laporan',
        'id_layanan',
        'nama',
        'nik',
        'alamat',
        'laporan',
        'status',
        'no_kk',
        'no_bpjs',
        'foto',
        'surat_pengantar',
        'kk',
        'ktp',
        'bpjs',
        'status_data',
        'jenis_izin',
        'transkrip',
        'surat_aktif',
        'foto_rumah',
        'SKTM',
        'Laporan_insidentil',
        'kejadian',
        'foto_rumah',
        'rekomendasi',
        'Suratpermohonan',
        'SKB',
        'SKKJ',
        'SKFOR',
        'akte_cota',
        'SKCK',
        'akte_nikah',
        'SKP',
        'SPPC',
        'SPM',
        'SPCAD',
        'SPCA',
        'SPWT',
        'SPHW',
        'SPAK',
        'LSCAA',
        'SKIPA',
        'SBAPK',
        'SBAPY',
        'SPPA',
        'SBACA',
        'LPAS',
        'foto_cota_caa',
        'sktm',
        'surat_rujukan',
        'foto_jkn',
        'foto_rawat',
        'no_hp',
        'skdk',
        'berita_acara',
        'ziarah',
        'nama_organisasi',
        'alamat_organisasi',
        'waktu_pendirian',
        'susunan_pengurus',
        'kegiatan_sosial',
        'maksud_tujuan',
        'waktu_penyelenggaraan',
        'luas_wilayah',
        'cara_penyelenggaraan',
        'rencana_anggaran',
        'surat_permohonan_operasional',
        'akta_pendirian',
        'anggaran_dasar',
        'riwayat_sejarah',
        'program_kerja',
        'daftar_pelayanan',
        'alamat_sekretariat',
        'sumber_pembiayaan',
        'izin_domisili',
        'rekomendasi_registrasi',
        'npwp',
        'rekening_bank',
        'foto_ktp_pengurus',
    ];
}

